### ISSUE TITLE
Rstudio Crashes after I close the shiny app (using pool package)

### ISSUE THREAD

**Issue by corinabioinformatic** [rstudio/pool#137] opened 2022-12-30 10:05 UTC
I basically have an shiny app like [in this example](https://shiny.rstudio.com/articles/pool-basics.html):
```
library(shiny)
library(DBI)
library(pool)

# create the connection
pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest"
)
onStop(function() {
  message("closing...")
  pool::poolClose(pool)
})

# === UI ====
ui <- fluidPage(
  textInput("ID", "Enter your ID:", "5"),
  tableOutput("tbl"),
  numericInput("nrows", "How many cities to show?", 10),
  plotOutput("popPlot")
)

#==== SERVER ====
server <- function(input, output, session) {
  output$tbl <- renderTable({
    sql <- "SELECT * FROM City WHERE ID = ?id;"
    query <- sqlInterpolate(pool, sql, id = input$ID)
    dbGetQuery(pool, query)
  })
  output$popPlot <- renderPlot({
    query <- paste0("SELECT * FROM City LIMIT ",
                    as.integer(input$nrows)[1], ";")
    df <- dbGetQuery(pool, query)
    pop <- df$Population
    names(pop) <- df$Name
    barplot(pop)
  })
}

#=== Run the App====
shinyApp(ui, server)

```
And the error has been already asked in [this post](https://community.rstudio.com/t/rstudio-crashes-after-i-close-the-shiny-app/7668) years ago, but the answer does not solve the issue on my side. (they suggest to get the latest "later" package, but I did and the error remains).
So the error is that: once I click on the Stop bottom on my RStudio Server Session (to stop the shiny App dashboard that runs fine) it does not stop. Instead, a window pop-out appears saying: *Terminate R* (And no message error appears in the console)
[![risnotresponding_whenstoptheshinyapp][1]][1]

  [1]: https://i.stack.imgur.com/2wOJE.png

I tried for hours to solve this annoyin behaviour (it makes me recall the system environment variables everytime I restart the Rstudio session) and I found a temporal solution: pressing **"Esc"** button on the "Console", to Stop the process, avoiding that "Terminate R" pop-out. Then it really stops and I can rerun again the Shiny app. I want to remark that the "Stop" icon (see circle in red, on the attached picture)does not work properly. The "Esc" works instead. 
Anybody knows why is this happening? I will also report it in GitHub "pool" issues. Although I am not completely sure if the issue is from the package.

_I am using R.4.1.0 (also my connection is to Postgress using a odbc driver, but is not displayed in the code. My session is running in RStudio Workbench 2021.092 (Build 382.pro1). I am ussing "pool" v.0.1.6._

I already reported the issue in Stackoverflow ([here](https://stackoverflow.com/questions/74955128/rstudio-crashes-after-i-close-the-shiny-app-using-pool-package))

**Comment by jcheng5** [comment] 2022-12-31 20:48
Hmmm, I'm not able to reproduce this. Does the problem still reproduce for you if you remove:
```
onStop(function() {
  message("closing...")
  pool::poolClose(pool)
})
```

**Comment by hadley** [comment] 2023-01-06 23:11
I can't reproduce this either. Sometimes this sort of error is due to installing incompatible binary versions of packages, so it might be worth closing all open R/RStudio sessions, deleting all the packages you have installed, and then re-installing.

**Closed by hadley** 2023-01-06 23:11 UTC
