### ISSUE TITLE
Pool dependency: leaked pool object warnings

### ISSUE THREAD

**Issue by majr-red** [rstudio/pool#135] opened 2022-08-26 17:23 UTC
I am trying to use `pool` inside a package. I create a `pool` object in a new environment (as [described in r-pkgs](https://r-pkgs.org/check.html#r-code)) during `.onLoad()` and destroy it in `.onUnload()`. 

I've created a reprex package here: https://github.com/majr-red/poolLeakReprex. 

Loading and unloading works fine, with
```r
devtools::load_all()
devtools::unload()
```
and `devtools::test()` passes, but `devtools::check()` is throwing this warning:

> Warning message:
> In (function (e)  : You have a leaked pooled object.

which I have been able to reproduce with:
```r
devtools::load_all()
devtools::load_all()
devtools::unload()
```

I have [read](https://github.com/rstudio/pool/issues/21) that this warning is expected when objects are checked out and not returned, but I don't check out any objects from the pool. 

So my question is: **Is this the expected behaviour?**

(I've also tried, as a workaround, _not_ creating and destroying the pool object, just exposing the create and destroy functions - which also works interactively but `R CMD check` seems to lock the testing environment, so then it throws an error.)

Many thanks for any guidance, and also for creating the pool package, which is fantastic!

**Comment by jcheng5** [comment] 2022-08-26 18:36
It's a bug. Here's a minimal repro:
```
library(pool)

local({
  poolCreate(new.env)
})
gc()
gc()
```

**Comment by jcheng5** [comment] 2022-08-26 18:40
Spoke too soon; my last attempt didn't close the pool. Here's a correct attempt at a repro, which doesn't repro:
```r
library(pool)

local({
  pool <- poolCreate(new.env)
  poolClose(pool)
})
gc()
gc()
```

**Comment by jcheng5** [comment] 2022-08-26 18:56
OK, I see. The problem is that `devtools::load_all()` doesn't cause `.onUnload` to be called on the previous version of the package. If you feel strongly about it, please file an issue on devtools. However, you could also argue that a garbage-collected pool should maybe close itself? I'm not confident 

In the case of your package, I highly recommend you not use the onLoad/onUnload approach. This:
```r
#' Namespace Parent
#' @return The parent env of the package namespace, not locked after loading
nsp <- function(){
  rlang::env_parent(n=2)
}
```
is the most problematic bit; storing this value outside of the package namespace feels dangerous. Instead, I recommend you replace that entire file with this:

```r
getConn <- local({
  poolInstance <- NULL
  function() {
    if (is.null(poolInstance)) {
      poolInstance <<- pool::dbPool(drv=RSQLite::SQLite(), Server=":memory:")
      # The following line is what prevents the leaked object warning
      reg.finalizer(poolInstance, poolClose)
    }
    poolInstance
  }
})
```

This keeps the caching of `getConn` very close to the implementation, and there's no chance of another function or package interfering with it.

---

In the future, if you want to have mutable variables at the package level, I recommend creating an environment variable in the package namespace:
```r
e <- new.env(parent=emptyenv())
```
This works great and does not have any of the downsides of writing to the parent environment.

**Closed by jcheng5** 2022-08-26 18:56 UTC

**Comment by majr-red** [comment] 2022-08-27 07:01
Thank you, this is so helpful both for my package and for my understanding. I started by trying to use:
```r
e <- new.env(parent=emptyenv())
```
in the package namespace but get 'locked environment' errors when I try to mutate the bindings in `e` - that was why I was creating it in the 'imports' namespace, which does not lock after loading. I agree this approach feels uncomfortable though; I'll persevere with your suggestion.
